# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f3738f37096cc76b0326a76b0b443812d466e354839b9d2edcc45d98e634fe0fbaea5675519f99717af22d58e32fb73f6b0517165dc25f2fd081be19a7f88b96

test:
  secret_key_base: 88daff6f9353ef8da5f27c8d5cbeac40b2d8b5850f1c3721d53bcfc89b7f37281e93182a252b24088643334c766042bb3fec5d88df7164478c630a2a1d8b4123

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
